apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aperium.frontendFullname" . }}
  labels:
    {{- include "aperium.frontendLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "aperium.frontendSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aperium.frontendSelectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "aperium.serviceAccountName" . }}
      containers:
        - name: aperium-frontend
          image: "{{ .Values.image.frontendRepository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.containerPort }}
              protocol: TCP
          readinessProbe:
            {{- toYaml .Values.frontend.probes.readiness | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.frontend.probes.liveness | nindent 12 }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
