{{- if .Values.externalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecret.targetName | quote }}
  labels:
    {{- include "aperium.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.externalSecret.clusterSecretStoreName | quote }}
  target:
    name: {{ .Values.externalSecret.targetName | quote }}
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.externalSecret.secretKey | quote }}
      remoteRef:
        key: {{ .Values.externalSecret.remoteSecretName | quote }}
{{- end }}
