{{- if .Values.redisUrlExternalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.redisUrlExternalSecret.targetName | quote }}
  labels:
    {{- include "aperium.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.redisUrlExternalSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.redisUrlExternalSecret.clusterSecretStoreName | quote }}
  target:
    name: {{ .Values.redisUrlExternalSecret.targetName | quote }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        REDIS_ENABLED: "true"
        REDIS_URL: {{ printf "{{ .redisUrl }}" | quote }}
  data:
    - secretKey: redisUrl
      remoteRef:
        key: {{ .Values.redisUrlExternalSecret.remoteSecretName | quote }}
{{- end }}
