{{- if .Values.qdrantApiKeysExternalSecret.enabled }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.qdrantApiKeysExternalSecret.targetName | quote }}
  labels:
    {{- include "aperium.labels" . | nindent 4 }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.qdrantApiKeysExternalSecret.refreshInterval | quote }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.qdrantApiKeysExternalSecret.clusterSecretStoreName | quote }}
  target:
    name: {{ .Values.qdrantApiKeysExternalSecret.targetName | quote }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        api-key: {{ printf "{{ .apiKey }}" | quote }}
        read-only-api-key: {{ printf "{{ .readOnlyApiKey }}" | quote }}
  data:
    - secretKey: apiKey
      remoteRef:
        key: {{ .Values.qdrantApiKeysExternalSecret.remoteSecretName | quote }}
        property: apiKey
    - secretKey: readOnlyApiKey
      remoteRef:
        key: {{ .Values.qdrantApiKeysExternalSecret.remoteSecretName | quote }}
        property: readOnlyApiKey
{{- end }}
