apiVersion: v1
kind: Service
metadata:
  name: {{ include "aperium.frontendFullname" . }}
  labels:
    {{- include "aperium.frontendLabels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "aperium.frontendSelectorLabels" . | nindent 4 }}
