apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.name }}
  annotations:
    argocd.argoproj.io/sync-wave: {{ .Values.syncWaves.secret | quote }}
spec:
  refreshInterval: {{ .Values.secrets.refreshInterval }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secrets.clusterSecretStoreName }}
  target:
    name: {{ .Values.secrets.name }}
    template:
      type: Opaque
    creationPolicy: Owner
  data:
    - secretKey: {{ .Values.secrets.authToken.secretKey | default "mcp_auth_token" }}
      remoteRef:
        key: {{ .Values.secrets.authToken.gcpSecretName }}
