apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argo-cd
spec:
  project: tools
  sources:
    - chart: external-secrets
      repoURL: https://charts.external-secrets.io/
      targetRevision: 0.20.4
      helm:
        valueFiles:
          - $values/envs/aperium-apps-prod/values/external-secrets.yaml
    - repoURL: https://github.com/YOUR_ORG/aperium-reference-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
