apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keda
  namespace: argo-cd
spec:
  project: tools
  sources:
    - chart: keda
      repoURL: https://kedacore.github.io/charts
      targetRevision: 2.19.0
      helm:
        valueFiles:
          - $values/envs/aperium-apps-prod/values/keda.yaml
    - repoURL: https://github.com/YOUR_ORG/aperium-reference-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: keda
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
