apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: stakater-reloader
  namespace: argo-cd
spec:
  project: tools
  sources:
    - chart: reloader
      repoURL: https://stakater.github.io/stakater-charts
      targetRevision: 2.2.7
      helm:
        valueFiles:
          - $values/envs/aperium-apps-prod/values/stakater.yaml
    - repoURL: https://github.com/YOUR_ORG/aperium-reference-infra.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: stakater
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
