replicaCount: 1

image:
  repository: nginxinc/nginx-unprivileged
  tag: "stable-alpine"
  pullPolicy: IfNotPresent

containerPort: 8080

service:
  type: ClusterIP
  port: 80

podAnnotations: {}

podSecurityContext:
  runAsNonRoot: true
  runAsUser: 10001
  runAsGroup: 10001
  fsGroup: 10001
  seccompProfile:
    type: RuntimeDefault

securityContext:
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL

extraVolumeMounts:
  - name: tmp
    mountPath: /tmp
  - name: cache
    mountPath: /var/cache/nginx
  - name: run
    mountPath: /var/run

extraVolumes:
  - name: tmp
    emptyDir: {}
  - name: cache
    emptyDir: {}
  - name: run
    emptyDir: {}

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 50m
    memory: 64Mi

gatewayApi:
  enabled: false
  gateway:
    name: public-gw
    namespace: gateway-infra
  securityPolicyName: ""
  iap:
    enabled: false
    clientID: ""
    oauthSecretName: ""
  hosts: []
    # - name: gateway-smoke
    #   host: gateway-smoke.apps.YOUR_DOMAIN
