{{- if .Values.argoSync.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-sync
  namespace: {{ .Values.argoCd.namespace }}
spec:
  project: tools
  source:
    repoURL: {{ .Values.argoSync.repoURL }}
    targetRevision: {{ .Values.argoSync.targetRevision | default "main" }}
    path: {{ .Values.argoSync.path | default "envs/aperium-apps-prod/argo" }}
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{- end }}
