{{- if .Values.iap.enabled }}
apiVersion: external-secrets.io/v1
kind: ClusterExternalSecret
metadata:
  name: {{ .Values.iap.oauthSecretName }}
  labels:
    {{- include "gke-gateway-api.labels" . | nindent 4 }}
spec:
  refreshTime: {{ .Values.clusterExternalSecrets.refreshInterval | quote }}
  namespaceSelector:
    matchLabels:
      gke-gateway-iap: "true"
  externalSecretSpec:
    refreshInterval: {{ .Values.clusterExternalSecrets.refreshInterval | quote }}
    secretStoreRef:
      kind: ClusterSecretStore
      name: {{ .Values.clusterExternalSecrets.storeName }}
    target:
      name: {{ .Values.iap.oauthSecretName }}
      creationPolicy: Owner
    data:
      - secretKey: key
        remoteRef:
          key: {{ .Values.clusterExternalSecrets.oauthSecret.remoteKey }}
{{- end }}
