apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.apiKeys.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: {{ .Values.secrets.apiKeys.refreshInterval | quote }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secrets.storeName }}
  target:
    name: {{ .Values.secrets.apiKeys.name }}
    creationPolicy: Owner
    template:
      type: Opaque
      data:
        api-key: {{ printf "{{ .apiKey }}" | quote }}
        read-only-api-key: {{ printf "{{ .readOnlyApiKey }}" | quote }}
  data:
    - secretKey: apiKey
      remoteRef:
        key: {{ .Values.secrets.apiKeys.remoteSecretKey }}
        property: apiKey
    - secretKey: readOnlyApiKey
      remoteRef:
        key: {{ .Values.secrets.apiKeys.remoteSecretKey }}
        property: readOnlyApiKey
