# N.B. prefect expects a secret w/ key "auth-string"
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .Values.secrets.adminPass.name }}
spec:
  refreshInterval: 1h0m0s           # rate SecretManager pulls GCPSM
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secrets.storeName }}
  target:
    # name of the k8s Secret to be created
    name: {{ .Values.secrets.adminPass.name }}
    template:
      type: Opaque
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ .Values.secrets.adminPass.name }} # GCP secret name
